### ISSUE TITLE
Running under unit test context - supported?

### ISSUE THREAD

**Issue by mandrolic** [mbrit/MetroLog#31]
I get a lot of this when running unit tests. I see some references in the code to a mode/config for running under test. Is there an easy way?

7|2013-08-06T20:29:47.3249436+00:00|TRACE|7|Logging operation failed. --> System.TypeInitializationException: The type initializer for 'MetroLog.LogWriteContext' threw an exception. ---> System.PlatformNotSupportedException: This API is not supported on this platform.
   at MetroLog.Internal.PlatformAdapter.Resolve[T](Boolean throwIfNotFound, Object[] args)
   at MetroLog.LogWriteContext..cctor()
   --- End of inner exception stack trace ---
   at MetroLog.LogWriteContext..ctor()
   at MetroLog.Internal.Logger.LogInternal(LogLevel level, String message, Object[] ps, Exception ex, Boolean doFormat)

**Comment by onovotny** [comment]
Closing for now. Please reopen if still an issue.
